[package]
name = "sig-scan"
version = "0.1.0"
authors = ["Rerumu"]
edition = "2018"
description = "A simple utility for scanning files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
